version: '3'
volumes:
        wordpress:
                driver: local
                driver_opts:
                        device: /home/akambou/Desktop/Inception/srcs/wordpress
                        o: bind
                        type: none
        mariadb:
                driver: local
                driver_opts:
                        device: /home/akambou/Desktop/Inception/srcs/mariadb
                        o: bind
                        type: none

services:
        nginx:
                container_name: nginx
                build: ./requirements/nginx
                ports:
                        - "443:443"
                depends_on: 
                        - wordpress
                volumes:
                        - wordpress:/var/www/html
                networks:
                        - inception
                env_file:
                        - .env
                restart: always

        wordpress:
                container_name: wordpress
                build: ./requirements/wordpress
                env_file:
                        - .env
                volumes:
                        - wordpress:/var/www/html
                networks:
                        - inception
                restart: always

        mariadb:
                container_name: mariadb
                build: ./requirements/mariadb
                volumes:
                        - mariadb:/var/lib/mysql
                env_file:
                        - .env
                networks:
                        - inception
                restart: always

networks:
        inception:
                driver: bridge